config/routes.rb
Rails.application.routes.draw do
     resources  :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id           :integer          not null, primary key
#  make         :string           not null
#  model        :string           not null
#  year         :integer          not null
#  vin          :string           not null
#  color        :string           default("black")
#  category     :string           default("car")
#  cylinders    :integer          default(4)
#  displacement :float            default(0.0)
#  mpg          :integer          default(0)
#  hp           :integer          default(0)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Car < ApplicationRecord
    before_validation :upper_vin, :upper_category,:check_vin
    
    
    validates :make, :model, :year, presence: true
    validates :vin, uniqueness: true, length: {is: 17}
    validates :make, uniqueness: { scope: [:model, :year]}
    validates :category, inclusion: { in: %w(CAR SPORT SUV TRUCK), message: "%{value} is not a valid category" }
    validates :cylinders, numericality: { only_integer: true, even: true, greater_than_or_equal_to: 4, less_than_or_equal_to: 12 , other_than: 10}
    validates :year, numericality: { only_integer: true,  greater_than_or_equal_to: 1900, less_than_or_equal_to: 2020}
   
    
    private 
    
    def upper_vin
        self.vin = self.vin.upcase if self.vin
    end
    
     def upper_category
        self.category = self.category.upcase if self.category
    end
    
    def check_vin
        self.errors.add(:vin, 'invalid representation') if self.vin && self.vin !~ /^[0-9A-Z]{17}$/
    end
    
   
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController <ApplicationController
    def index
        @cars = Car.all
    end
    
    def show
        
        @car = Car.find(params[:id])
    end
    
    def destroy
       
        car = Car.find(params[:id])
        car.destroy
       
        redirect_to cars_path

    end
    
    def new
        @car = Car.new
    end
    
    def create
        @car = Car.new(params[:car].permit(:vin, :make, :model, :year))
       
        if  @car.save
            redirect_to car_path(@car)
        else
           
            render 'new'
        end
    
    end
    
    def edit
        @car = Car.find(params[:id])
    
    end
    
    def update
        @car = Car.find(params[:id])
        
        @car.vin = params[:car].permit([:vin])
        @car.make = params[:car].permit([:make])
        @car.model = params[:car].permit([:model])
        @car.year = params[:car].permit([:year])
        
       
        
        if  @car.update
            redirect_to car_path(@car)
        else
           
            render 'edit'
        end
        
        
    end
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<h1>Edit Car</h1>
<%= form_with(url: "/cars/#{@car.id}", model: @car, local: true , method: :patch) do |form| %>  
        <% if @car.errors.any? %>    
            <div id="error_explanation">     
                <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>     
                
                <ul>      
                    <% @car.errors.full_messages.each do |message| %>        
                        <li><%= message %></li>     
        <% end %>     
                </ul>   
            </div> 
        <% end %>  
    <div class="field">   
        <%= form.label :vin %>
        <%= form.text_field :vin, id: :car_vin,  value: @car.vin %>  
    </div> 
    <div class="field">  
        <%= form.label :make %>   
        <%= form.text_field :make, id: :car_make, value: @car.make %>  
    </div>  
    <div class="field">   
        <%= form.label :model %>  
        <%= form.text_field :model, id: :car_model, value: @car.model%>  
    </div> 
    <div class="field">
        <%= form.label :year %>   
        <%= form.number_field :year, id: :car_year, value: @car.year%> 
    </div>  
    <div class="actions">    
        <%= form.submit 'Edit Car' %>
    </div> 
<% end %>

app/views/cars/index.html.erb
<h1>Cars</h1>

<div>
    
    <%= link_to  'New', new_car_path %>
</div>
<table>
    <thead>
        <th>VIN</th>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
    </thead>
    <tbody>
        <% @cars.each do |c| %>
        <tr>
            <td><%= link_to c.vin,c %></td>
            <td><%= c.make %></td>
            <td><%= c.model %></td>
            <td><%= c.year %></td>
        </tr>
        
        
        <% end %>
        
    </tbody>
    
</table>

app/views/cars/new.html.erb
<h1>Add New Car</h1>

<%= form_with(model: @car, local: true) do |form| %>  
        <% if @car.errors.any? %>    
            <div id="error_explanation">     
                <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>     
                
                <ul>      
                    <% @car.errors.full_messages.each do |message| %>        
                        <li><%= message %></li>     
        <% end %>     
                </ul>   
            </div> 
        <% end %>  
    <div class="field">   
        <%= form.label :vin %>
        <%= form.text_field :vin, id: :car_vin %>  
    </div> 
    <div class="field">  
        <%= form.label :make %>   
        <%= form.text_field :make, id: :car_make %>  
    </div>  
    <div class="field">   
        <%= form.label :model %>  
        <%= form.text_field :model, id: :car_model %>  
    </div> 
    <div class="field">
        <%= form.label :year %>   
        <%= form.number_field :year, id: :car_year %> 
    </div>  
    <div class="actions">    
        <%= form.submit %>
    </div> 
<% end %>

app/views/cars/show.html.erb
<h1>Car Details for <%=@car.vin %></h1>

<div>
    <span><%= link_to 'Edit', edit_car_path(@car) %></span>
    
    <span><%= link_to 'Delete', car_path(@car) , method: :delete %></span>
    
</div>

<div> Make: <%= @car.make%></div>
<div> Make: <%= @car.model%></div>
<div> Make: <%= @car.year%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dealer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>